export { default as SuspenseLoader } from './suspense-loader';
export { default as Navbar } from './navbar';
export { default as Footer } from './footer';
export { default as TopNav } from './top-nav';
export { default as Button } from './button';
export { default as SectionsTitle } from './sections-title';
export { default as SectionsWrapper } from './sections-wrapper';
export { default as WebsiteCard } from './website-card';
export { default as Tabs } from './tabs';
export { default as Counter } from './counter';
export { default as ProjectsImages } from './projects-images';
export { default as PagesWrapper } from './page-wrapper';
export { default as ChangeLanguage } from './change-language';
export { default as BiLang } from './bi-lang-comp';
export { default as ProjectsSection } from './project-section';
export { default as Services } from './services-section';
export { default as PagesHeader } from './pages-header';
export { default as ContentWithImageComp } from './content-with-img-comp';
export { default as Subtext } from './subtext';
export { default as MoreBtnLink } from './more-btn-link';
export { default as DetailsModal } from './details-modal';
export { default as PageWrapper } from './page-wrapper';

export * from './icons';
